{{ if and .Values.scaling.enabled (empty .Values.scaling.cpu) .Values.scaling.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azp-agent.autoscaler.fullname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
    {{- include "azp-agent.stringDict" .Values.scaling.serviceAccount.labels | nindent 4 }}
  {{- if .Values.scaling.serviceAccount.annotations }}
  annotations:
    {{- include "azp-agent.stringDict" .Values.scaling.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{ end }}
