{{- if and .Values.scaling.enabled (empty .Values.scaling.cpu) .Values.scaling.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "azp-agent.fullname" . }}-autoscaler
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "azp-agent.selector" . | nindent 6 }}
      component: autoscaler
{{- end }}
