{{- if and .Values.scaling.enabled (empty .Values.scaling.cpu) .Values.scaling.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "azp-agent.fullname" . }}-autoscaler
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "azp-agent.fullname" . }}-autoscaler
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "azp-agent.autoscaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
