{{- if and .Values.scaling.enabled (empty .Values.scaling.cpu) (or .Values.scaling.rbac.psp.enabled .Values.scaling.rbac.psp.name) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "azp-agent.autoscaler.psp.rbacname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "azp-agent.autoscaler.psp.name" . }}
{{- end -}}
