{{ if and .Values.scaling.enabled (empty .Values.scaling.cpu) .Values.scaling.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azp-agent.fullname" . }}-autoscaler
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
{{ end }}
