{{- if and .Values.scaling.enabled (empty .Values.scaling.cpu) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "azp-agent.autoscaler.fullname" . }}-metrics
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 10101
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "azp-agent.selector" . | nindent 4 }}
    component: autoscaler
{{- end }}
