{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "azp-agent.fullname" . | quote }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: agent
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "azp-agent.selector" . | nindent 6 }}
      component: agent
{{- end }}
