apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent.fullname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.azp.existingSecret) (not .Values.azp.existingSecretKey) }}
  azp-token: {{ .Values.azp.token | required "The Azure Pipeline Token is required!" | b64enc | quote }}
  {{- end }}
  {{- range .Values.azp.extraEnv }}
    {{- if .secret }}
  {{ .name | quote }}: {{ .value | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- range .Values.docker.extraEnv }}
    {{- if .secret }}
  {{ .name | quote }}: {{ .value | b64enc | quote }}
    {{- end }}
  {{- end }}
