apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent.fullname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
type: Opaque
data:
  azp-token: {{ .Values.azp.token | required "The Azure Pipeline Token is required!" | b64enc | quote }}
  {{- range .Values.extraEnv }}
  {{- if .secret }}
  {{ .name | quote }}: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
