{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azp-agent.fullname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: agent
    {{- include "azp-agent.stringDict" .Values.serviceAccount.labels | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- include "azp-agent.stringDict" .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{ end }}
