apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "azp-agent.fullname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    {{- include "azp-agent.stringDict" .Values.labels | nindent 4 }}
  annotations:
    {{- include "azp-agent.stringDict" .Values.annotations | nindent 4 }}
{{ $combinePVT := (and .Values.azp.persistence.enabled .Values.docker.persistence.enabled (eq .Values.azp.persistence.name .Values.docker.persistence.name)) }}
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  serviceName: {{ include "azp-agent.fullname" . }}
  selector:
    matchLabels:
      {{- include "azp-agent.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "azp-agent.labels" . | nindent 8 }}
        {{- include "azp-agent.stringDict" .Values.podLabels | nindent 8 }}
      annotations:
        {{- include "azp-agent.stringDict" .Values.podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.azp.image.repository }}:{{ .Values.azp.image.tag }}"
        imagePullPolicy: {{ .Values.azp.image.pullPolicy }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZP_WORK
          value: {{ .Values.azp.workspace | quote }}
        - name: AZP_URL
          value: {{ .Values.azp.url | required "The Azure Devops URL is required!" | quote }}
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "azp-agent.fullname" . }}
              key: azp-token
        - name: AZP_POOL
          value: {{ .Values.azp.pool | quote }}
        - name: AZP_AGENT_NAME
          value: {{ .Values.azp.agentName | quote }}
        {{- if .Values.docker.enabled }}
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
        {{- end }}
        - name: DEBIAN_FRONTEND
          value: 'noninteractive'
        {{- range .Values.azp.extraEnv }}
        - name: {{ .name | quote }}
          {{- if .secret }}
          valueFrom:
            secretKeyRef:
              name: {{ include "azp-agent.fullname" . }}
              key: {{ .name | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{ .valueFrom | toYaml | nindent 12 }}
          {{- else }}
          value: {{ .value | required (printf "A value is required for environment variable %s" .name) | quote }}
          {{- end }}
        {{- end }}
        workingDir: /azp
        command:
        - '/azp/start.sh'
        {{- with .Values.azp.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.azp.persistence.name | quote }}
          mountPath: {{ .Values.azp.workspace | quote }}
          {{- if $combinePVT }}
          subPath: 'workspace'
          {{- end }}
        - name: scripts
          mountPath: "/azp/start.sh"
          subPath: "start.sh"
          readOnly: true
        {{- if .Values.azp.extraVolumeMounts }}
          {{- .Values.azp.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.azp.lifecycle }}
        lifecycle:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      
      {{- if .Values.docker.enabled }}
      - name: docker-daemon
        image: "{{ .Values.docker.image.repository }}:{{ .Values.docker.image.tag }}"
        imagePullPolicy: {{ .Values.docker.image.pullPolicy }}
        ports:
        - name: docker-daemon
          containerPort: 2375
        env:
        {{- range .Values.docker.extraEnv }}
        - name: {{ .name | quote }}
          {{- if .secret }}
          valueFrom:
            secretKeyRef:
              name: {{ include "azp-agent.fullname" . }}
              key: {{ .name | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{ .valueFrom | toYaml | nindent 12 }}
          {{- else }}
          value: {{ .value | required (printf "A value is required for environment variable %s" .name) | quote }}
          {{- end }}
        {{- end }}
        securityContext:
          privileged: true
        {{- with .Values.docker.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.docker.persistence.name | quote }}
          mountPath: "/var/lib/docker"
          {{- if $combinePVT }}
          subPath: 'docker'
          {{- end }}
        {{- if .Values.docker.extraVolumeMounts }}
          {{- .Values.docker.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.docker.lifecycle }}
        lifecycle:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.sidecars }}
        {{- .Values.sidecars | toYaml | nindent 6 }}
      {{- end }}
      
      volumes:
      {{- if not .Values.azp.persistence.enabled }}
      - name: {{ .Values.azp.persistence.name | quote }}
        emptyDir: {}
      {{- end }}
      {{- if not .Values.docker.persistence.enabled }}
      - name: {{ .Values.docker.persistence.name | quote }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "azp-agent.fullname" . }}
          defaultMode: 0554
      {{- if .Values.extraVolumes }}
        {{- .Values.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
      
      {{- with .Values.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      
      {{- if .Values.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{ with .Values.dnsConfig }}
      dnsConfig:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- if .Values.priority }}
      priority: {{ .Value.priority }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Value.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.priority }}
      priority: {{ .Values.priority }}
      {{- end }}
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Value.runtimeClassName | quote }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Value.schedulerName | quote }}
      {{- end }}
  
  volumeClaimTemplates:
  {{- if .Values.azp.persistence.enabled }}
    {{- include "azp-agent.volumeClaimTemplate" (dict "root" . "data" .Values.azp.persistence) | nindent 2 }}
  {{- end }}
  {{- if and (not $combinePVT) .Values.docker.enabled .Values.docker.persistence.enabled }}
    {{- include "azp-agent.volumeClaimTemplate" (dict "root" . "data" .Values.docker.persistence) | nindent 2 }}
  {{- end }}
  {{- if .Values.extraVolumeClaimTemplates }}
    {{- .Values.extraVolumeClaimTemplates | toYaml | nindent 2 }}
  {{- end }}

{{- define "azp-agent.volumeClaimTemplate" -}}
- metadata:
    name: {{ .data.name | quote }}
    labels:
      {{- include "azp-agent.labels" .root | nindent 6 }}
      {{- include "azp-agent.stringDict" .data.labels | nindent 6 }}
    annotations:
      {{- include "azp-agent.stringDict" .data.annotations | nindent 6 }}
  spec:
    accessModes:
      {{- .data.accessModes | toYaml | nindent 4 }}
    selector:
      {{- .data.selector | toYaml | nindent 6 }}
    resources:
      requests:
        storage: {{ .data.storage }}
      {{- if .data.storageLimit }}
      limits:
        storage: {{ .data.storageLimit }}
      {{- end }}
    storageClassName: {{ .data.storageClassName | quote }}
{{- end -}}
